Instructional_Materials/Weekend_11/Examples/vet_app-1/config/routes.rb
Rails.application.routes.draw do
  root 'pets#index'
  resources :pets
end

Instructional_Materials/Weekend_11/Examples/vet_app-1/app/models/pet.rb
class Pet < ActiveRecord::Base

end

Instructional_Materials/Weekend_11/Examples/vet_app-1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Instructional_Materials/Weekend_11/Examples/vet_app-1/app/controllers/pets_controller.rb
class PetsController < ApplicationController

  #listing of all the pets that are part of the vet clinic
  #pets_index, localhost:3000/pets
  #views/pets/index.html.erb
  def index
    @pets = Pet.order(:name)
  end

  #listing of information for an individual pet
  #the controller finds the correct pet in the database by looking up the id
  #pet_path, localhost:3000/pets/[id=id number of individual pet]
  #so to see inforamtion about the first pet in the database, the url woudl be localhost:3000/pets/1
  #views/pets/show.html.erb
  def show
    @pet = Pet.find(params[:id])
  end

  #presents form to create a new pet at the clinic
  #new_pet, localhost:3000/pets/new
  def new
    @pet = Pet.new
  end

  #this route creates the new pet after submitting the form
  #we can't really access it as a page, as we don't need to see a page during this POST
  #create is tied to new. So it is the route that kicks in after the 'New pet' button is activated.
  def create
    Pet.create(pet_params)
    redirect_to pets_path
  end

  #allows us to edit the information about a pet
  #edit_pet_path, localhost:3000/pets/[id = id number of individual pet]
  def edit
    @pet = Pet.find(params[:id])
  end

  #update is linked to edit in the same way that create is linked to new (there is no page for update)
  #update is a POST request that updates the inforamtion in the database
  def update
    @pet = Pet.find(params[:id])
    @pet.update_attributes(pet_params)
    redirect_to pets_path
  end

  #destroy allows us to delete records as needed
  #it works like create and update: there is no separate views page for delete
  #for this app, you can destroy the record from the page for the record. So it's an option on the pet/[id] page
  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy
    redirect_to pets_path
  end

  private
#Private params are needed for create and update
#We need to pass in any of the parameters that are being sent to the app through a POST
#This params method ensures that harmful data (data that could affect or change our databases) will not get through. Rails will check that for us.

  def pet_params
    params.require(:pet).permit(:name, :species, :breed)
  end
end

Instructional_Materials/Weekend_11/Examples/vet_app-1/app/helpers/application_helper.rb
module ApplicationHelper
end

Instructional_Materials/Weekend_11/Examples/vet_app-1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VetApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <a href="<%= root_path %>" id="root">Home</a>

<%= yield %>

</body>
</html>

Instructional_Materials/Weekend_11/Examples/vet_app-1/app/views/pets/_form.html.erb
<%= form_for @pet do |f| %>
  <div class="form">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="form">
    <%= f.label :species %>
    <%= f.text_field :species %>
  </div>
  <div class="form">
    <%= f.label :breed %>
    <%= f.text_field :breed %>
  </div>
  <div class="form_button">
    <%= f.submit %>
  </div>
<% end %>

Instructional_Materials/Weekend_11/Examples/vet_app-1/app/views/pets/edit.html.erb
<h1 class="title">Update Pet Information</h1>

<%= render 'form' %>

Instructional_Materials/Weekend_11/Examples/vet_app-1/app/views/pets/index.html.erb
<div class="title">
  <h1>Welcome to our vet clinic!</h1>
<div>

<li>
  <% @pets.each do |pet| %>
    <%if pet.name%>
      <ul><a href="<%=pet_path(pet.id)%>" class="list_of_pets"><%= pet.name %></a></ul>
      <ul class="pet_info"><%= pet.species %>: <%=pet.breed %></ul>
      <% end %>
    <% end %>
</li>

<div class="new_pet">
  <a href="<%=new_pet_path%>" class="new_pet_link">Add a new pet</a>
</div>

Instructional_Materials/Weekend_11/Examples/vet_app-1/app/views/pets/new.html.erb
<h1 class="title">Add a new pet</h1>

<%= render "form" %>

Instructional_Materials/Weekend_11/Examples/vet_app-1/app/views/pets/show.html.erb
<li>
  <h1 class="title"><ul><%= @pet.name %></ul></h1>
  <ul class="pet_info">Species: <%= @pet.species %></ul>
  <ul class="pet_info">Breed: <%= @pet.breed %></ul>
</li>

<div class="bottom_of_show">
  <h4 class="edit_or_delete"><%= link_to "Edit Pet Information", edit_pet_path(@pet.id) %></h4>
  <h4 class="edit_or_delete"><%= link_to "Remove Pet", @pet, method: :delete %></h4>
</div>